module.exports = [
  "A great question is one that everyone asks, but only a few dare to answer."
  "Our capabilities are only limited by the limits we impose on ourselves."
  "An ideal world can never be achieved. That doesn't stop me from trying."
  "Do what you love, and try to love what you don't."
  "Some try to forget the past - others try to remember the future."
  "The future is what you make of it - so go make it awesome!"
  "When inspiration strikes, strike back!"
  "Ideas are hardly in short supply. It's the people who capture them who are."
  "Learning how to write code is like learning how to write: you can express yourself in ways you never thought were possible."
  "There's not a single action you make or a single word you say that doesn't reflect who you are. Embrace it."
  "The only person who can make you a better person is yourself."
  "We never truly forget - we just fail to remember."
  "Our identities are able to shape the way we think. Let the way you think shape your identity."
  "Great thoughts are not meant to be kept inside the head - Express yourself!"
  "Experiment to find your favorite medium: Creativity comes in countless different flavors."
  "You'll never know if you don't try. You can always try, even if you don't know."
  "The digital realm is an extraordinary thing: it's a world where in which the unreachable is suddenly tangible."
  "You can see anything, from what's in front of you to your wildest dreams. All you need to know is where to look."
  "Time will gladly be on your side if you let it."
  "Try thinking something no one else has thought before, because no one can think of everything!"
  "Thinking outside the box is only necessary if you box your own thoughts in."
  "It's hard to imagine how you'll be viewed a century or a millenia from now."
  "Unique individuals are homogenous, but homogenous individuals are not unique."
  "Let passion guide you and creativity get you there."
  "A passionate heart and a creative mind are a potent combination."
]
